<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ubigeo;

class UbigeoSeeder extends Seeder
{
    public function run()
    {
        $ubigeos = [
            // Lima
            ['codigo' => '150101', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'LIMA'],
            ['codigo' => '150102', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'ANCON'],
            ['codigo' => '150103', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'ATE'],
            ['codigo' => '150104', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'BARRANCO'],
            ['codigo' => '150105', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'BREÑA'],
            ['codigo' => '150106', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'CARABAYLLO'],
            ['codigo' => '150107', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'CHACLACAYO'],
            ['codigo' => '150108', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'CHORRILLOS'],
            ['codigo' => '150109', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'CIENEGUILLA'],
            ['codigo' => '150110', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'COMAS'],
            ['codigo' => '150111', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'EL AGUSTINO'],
            ['codigo' => '150112', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'INDEPENDENCIA'],
            ['codigo' => '150113', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'JESUS MARIA'],
            ['codigo' => '150114', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'LA MOLINA'],
            ['codigo' => '150115', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'LA VICTORIA'],
            ['codigo' => '150116', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'LIMA'],
            ['codigo' => '150117', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'LINCE'],
            ['codigo' => '150118', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'LOS OLIVOS'],
            ['codigo' => '150119', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'LURIGANCHO'],
            ['codigo' => '150120', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'LURIN'],
            ['codigo' => '150121', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'MAGDALENA DEL MAR'],
            ['codigo' => '150122', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'PUEBLO LIBRE'],
            ['codigo' => '150123', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'PUENTE PIEDRA'],
            ['codigo' => '150124', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'PUNTA HERMOSA'],
            ['codigo' => '150125', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'RIMAC'],
            ['codigo' => '150126', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SAN BARTOLO'],
            ['codigo' => '150127', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SAN BORJA'],
            ['codigo' => '150128', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SAN ISIDRO'],
            ['codigo' => '150129', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SAN JUAN DE LURIGANCHO'],
            ['codigo' => '150130', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SAN JUAN DE MIRAFLORES'],
            ['codigo' => '150131', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SAN LUIS'],
            ['codigo' => '150132', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SAN MARTIN DE PORRES'],
            ['codigo' => '150133', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SAN MIGUEL'],
            ['codigo' => '150134', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SANTA ANITA'],
            ['codigo' => '150135', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SANTIAGO DE SURCO'],
            ['codigo' => '150136', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'SURQUILLO'],
            ['codigo' => '150137', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'VILLA EL SALVADOR'],
            ['codigo' => '150138', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'VILLA MARIA DEL TRIUNFO'],
            ['codigo' => '150139', 'departamento' => 'LIMA', 'provincia' => 'LIMA', 'distrito' => 'MI PERU'],
            
            // Callao
            ['codigo' => '150201', 'departamento' => 'CALLAO', 'provincia' => 'CALLAO', 'distrito' => 'CALLAO'],
            ['codigo' => '150202', 'departamento' => 'CALLAO', 'provincia' => 'CALLAO', 'distrito' => 'BELLAVISTA'],
            ['codigo' => '150203', 'departamento' => 'CALLAO', 'provincia' => 'CALLAO', 'distrito' => 'Carmen de la Legua-Reynoso'],
            ['codigo' => '150204', 'departamento' => 'CALLAO', 'provincia' => 'CALLAO', 'distrito' => 'LA PERLA'],
            ['codigo' => '150205', 'departamento' => 'CALLAO', 'provincia' => 'CALLAO', 'distrito' => 'LA PUNTA'],
            ['codigo' => '150206', 'departamento' => 'CALLAO', 'provincia' => 'CALLAO', 'distrito' => 'VENTANILLA'],
            
            // Piura
            ['codigo' => '200101', 'departamento' => 'PIURA', 'provincia' => 'PIURA', 'distrito' => 'PIURA'],
            ['codigo' => '200102', 'departamento' => 'PIURA', 'provincia' => 'PIURA', 'distrito' => 'AYABACA'],
            ['codigo' => '200103', 'departamento' => 'PIURA', 'provincia' => 'PIURA', 'distrito' => 'CHULUCANAS'],
            ['codigo' => '200104', 'departamento' => 'PIURA', 'provincia' => 'PIURA', 'distrito' => 'EL TALLAN'],
            ['codigo' => '200105', 'departamento' => 'PIURA', 'provincia' => 'PIURA', 'distrito' => 'LA MATANZA'],
            ['codigo' => '200106', 'departamento' => 'PIURA', 'provincia' => 'PIURA', 'distrito' => 'LA UNION'],
            ['codigo' => '200107', 'departamento' => 'PIURA', 'provincia' => 'PIURA', 'distrito' => 'LAS LOMAS'],
            ['codigo' => '200108', 'departamento' => 'PIURA', 'provincia' => 'PIURA', 'distrito' => 'TAMBO GRANDE'],
            ['codigo' => '200201', 'departamento' => 'PIURA', 'provincia' => 'AYABACA', 'distrito' => 'AYABACA'],
            ['codigo' => '200202', 'departamento' => 'PIURA', 'provincia' => 'AYABACA', 'distrito' => 'FRONTERA'],
            ['codigo' => '200203', 'departamento' => 'PIURA', 'provincia' => 'AYABACA', 'distrito' => 'JILILI'],
            ['codigo' => '200204', 'departamento' => 'PIURA', 'provincia' => 'AYABACA', 'distrito' => 'LAGUNAS'],
            ['codigo' => '200205', 'departamento' => 'PIURA', 'provincia' => 'AYABACA', 'distrito' => 'MONTERO'],
            ['codigo' => '200206', 'departamento' => 'PIURA', 'provincia' => 'AYABACA', 'distrito' => 'PACARAOS'],
            ['codigo' => '200207', 'departamento' => 'PIURA', 'provincia' => 'AYABACA', 'distrito' => 'SISA'],
            ['codigo' => '200208', 'departamento' => 'PIURA', 'provincia' => 'AYABACA', 'distrito' => 'YAMANGO'],
            ['codigo' => '200301', 'departamento' => 'PIURA', 'provincia' => 'SULLANA', 'distrito' => 'SULLANA'],
            ['codigo' => '200302', 'departamento' => 'PIURA', 'provincia' => 'SULLANA', 'distrito' => 'BELLAVISTA'],
            ['codigo' => '200303', 'departamento' => 'PIURA', 'provincia' => 'SULLANA', 'distrito' => 'CARPANZAR'],
            ['codigo' => '200304', 'departamento' => 'PIURA', 'provincia' => 'SULLANA', 'distrito' => 'QUERECOTILLO'],
            ['codigo' => '200305', 'departamento' => 'PIURA', 'provincia' => 'SULLANA', 'distrito' => 'SALITRAL'],
            ['codigo' => '200306', 'departamento' => 'PIURA', 'provincia' => 'SULLANA', 'distrito' => 'SAN JUAN DE BIGOTE'],
            ['codigo' => '200307', 'departamento' => 'PIURA', 'provincia' => 'SULLANA', 'distrito' => 'SIGUAS'],
            ['codigo' => '200308', 'departamento' => 'PIURA', 'provincia' => 'SULLANA', 'distrito' => 'SAPILLICA'],
            ['codigo' => '200401', 'departamento' => 'PIURA', 'provincia' => 'TAMBOGRANDE', 'distrito' => 'TAMBOGRANDE'],
            ['codigo' => '200402', 'departamento' => 'PIURA', 'provincia' => 'TAMBOGRANDE', 'distrito' => 'BUENOS AIRES'],
            ['codigo' => '200403', 'departamento' => 'PIURA', 'provincia' => 'TAMBOGRANDE', 'distrito' => 'CRISTO NOS VALGA'],
            ['codigo' => '200404', 'departamento' => 'PIURA', 'provincia' => 'TAMBOGRANDE', 'distrito' => 'LA ESPERANZA'],
            ['codigo' => '200405', 'departamento' => 'PIURA', 'provincia' => 'TAMBOGRANDE', 'distrito' => 'PIORRO'],
            ['codigo' => '200406', 'departamento' => 'PIURA', 'provincia' => 'TAMBOGRANDE', 'distrito' => 'SAN MIGUEL'],
            ['codigo' => '200407', 'departamento' => 'PIURA', 'provincia' => 'TAMBOGRANDE', 'distrito' => 'CASITAS'],
            ['codigo' => '200408', 'departamento' => 'PIURA', 'provincia' => 'TAMBOGRANDE', 'distrito' => 'NARIGANTO'],
            
            // Lambayeque
            ['codigo' => '210101', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'CHICLAYO'],
            ['codigo' => '210102', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'CAN TACO'],
            ['codigo' => '210103', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'CHONOS'],
            ['codigo' => '210104', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'CONTA'],
            ['codigo' => '210105', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'LA FLORIDA'],
            ['codigo' => '210106', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'MOCHO'],
            ['codigo' => '210107', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'PIMENTEL'],
            ['codigo' => '210108', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'REQUE'],
            ['codigo' => '210109', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'SANTA ROSA'],
            ['codigo' => '210110', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'SAÑAL'],
            ['codigo' => '210111', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'CHICLAYO', 'distrito' => 'TONY'],
            ['codigo' => '210201', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'FERRENAFE', 'distrito' => 'FERRENAFE'],
            ['codigo' => '210202', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'FERRENAFE', 'distrito' => 'CAÑARIS'],
            ['codigo' => '210203', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'FERRENAFE', 'distrito' => 'ELECTO'],
            ['codigo' => '210204', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'FERRENAFE', 'distrito' => 'INCAHUASI'],
            ['codigo' => '210205', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'FERRENAFE', 'distrito' => 'MANUEL ANTONIO MESONES MURO'],
            ['codigo' => '210206', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'FERRENAFE', 'distrito' => 'PITIPO'],
            ['codigo' => '210207', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'FERRENAFE', 'distrito' => 'PUNO'],
            ['codigo' => '210301', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'LAMBAYEQUE'],
            ['codigo' => '210302', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'CHOCHOPE'],
            ['codigo' => '210303', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'COLONIA'],
            ['codigo' => '210304', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'JUANillo'],
            ['codigo' => '210305', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'MÓRrope'],
            ['codigo' => '210306', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'Motupe'],
            ['codigo' => '210307', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'OLMOS'],
            ['codigo' => '210308', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'PACAIPE'],
            ['codigo' => '210309', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'SALAS'],
            ['codigo' => '210310', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'SAN JOSE'],
            ['codigo' => '210311', 'departamento' => 'LAMBAYEQUE', 'provincia' => 'LAMBAYEQUE', 'distrito' => 'TUCUME'],
            
            // La Libertad
            ['codigo' => '220101', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'TRUJILLO'],
            ['codigo' => '220102', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'ALTO MOCHE'],
            ['codigo' => '220103', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'EL PORVENIR'],
            ['codigo' => '220104', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'FLORIDA'],
            ['codigo' => '220105', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'HUANCAYO'],
            ['codigo' => '220106', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'LA ESPERANZA'],
            ['codigo' => '220107', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'Laredo'],
            ['codigo' => '220108', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'MOCHE'],
            ['codigo' => '220109', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'POROTO'],
            ['codigo' => '220110', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'SALAVERRY'],
            ['codigo' => '220111', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'SIMBAL'],
            ['codigo' => '220112', 'departamento' => 'LA LIBERTAD', 'provincia' => 'TRUJILLO', 'distrito' => 'VIRU'],
            ['codigo' => '220201', 'departamento' => 'LA LIBERTAD', 'provincia' => 'CHEPEN', 'distrito' => 'CHEPEN'],
            ['codigo' => '220202', 'departamento' => 'LA LIBERTAD', 'provincia' => 'CHEPEN', 'distrito' => 'CHICAMA'],
            ['codigo' => '220203', 'departamento' => 'LA LIBERTAD', 'provincia' => 'CHEPEN', 'distrito' => 'CHONGoy'],
            ['codigo' => '220204', 'departamento' => 'LA LIBERTAD', 'provincia' => 'CHEPEN', 'distrito' => 'GUADALUPE'],
            ['codigo' => '220205', 'departamento' => 'LA LIBERTAD', 'provincia' => 'CHEPEN', 'distrito' => 'PACASMAYO'],
            ['codigo' => '220206', 'departamento' => 'LA LIBERTAD', 'provincia' => 'CHEPEN', 'distrito' => 'SAN JERONIMO'],
            ['codigo' => '220207', 'departamento' => 'LA LIBERTAD', 'provincia' => 'CHEPEN', 'distrito' => 'SAN PEDRO DE LLOC'],
            ['codigo' => '220208', 'departamento' => 'LA LIBERTAD', 'provincia' => 'CHEPEN', 'distrito' => 'TAJAMARCO'],
            ['codigo' => '220209', 'departamento' => 'LA LIBERTAD', 'provincia' => 'CHEPEN', 'distrito' => 'URBON'],
            ['codigo' => '220210', 'departamento' => 'LA LIBERTAD', 'provincia' => 'CHEPEN', 'distrito' => 'LUNAHUANCO'],
            
            // Arequipa
            ['codigo' => '240101', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'AREQUIPA'],
            ['codigo' => '240102', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'CAYMA'],
            ['codigo' => '240103', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'CERRO COLORADO'],
            ['codigo' => '240104', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'CHARACATO'],
            ['codigo' => '240105', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'CHIGUATA'],
            ['codigo' => '240106', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'LA JOYA'],
            ['codigo' => '240107', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'MARIANO MELGAR'],
            ['codigo' => '240108', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'MOLLENDO'],
            ['codigo' => '240109', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'PAUCARPATA'],
            ['codigo' => '240110', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'POCSI'],
            ['codigo' => '240111', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'POLONAY'],
            ['codigo' => '240112', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'QUEQUEÑA'],
            ['codigo' => '240113', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'SALINAS'],
            ['codigo' => '240114', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'SAN ISIDRO DE CALCA'],
            ['codigo' => '240115', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'SANTA ISABELL DE PORTADA'],
            ['codigo' => '240116', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'SANTA ROSA DE QUISHUARANI'],
            ['codigo' => '240117', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'SOCABAYA'],
            ['codigo' => '240118', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'VICTOR LOPEZ ARIAS'],
            ['codigo' => '240119', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'YARABAMBA'],
            ['codigo' => '240120', 'departamento' => 'AREQUIPA', 'provincia' => 'AREQUIPA', 'distrito' => 'YURA'],
            ['codigo' => '240201', 'departamento' => 'AREQUIPA', 'provincia' => 'CAMANA', 'distrito' => 'CAMANA'],
            ['codigo' => '240202', 'departamento' => 'AREQUIPA', 'provincia' => 'CAMANA', 'distrito' => 'COSTAX'],
            ['codigo' => '240203', 'departamento' => 'AREQUIPA', 'provincia' => 'CAMANA', 'distrito' => 'ISLAY'],
            ['codigo' => '240204', 'departamento' => 'AREQUIPA', 'provincia' => 'CAMANA', 'distrito' => 'MARIANO MELGAR'],
            ['codigo' => '240205', 'departamento' => 'AREQUIPA', 'provincia' => 'CAMANA', 'distrito' => 'MEJIA'],
            ['codigo' => '240206', 'departamento' => 'AREQUIPA', 'provincia' => 'CAMANA', 'distrito' => 'MOLLENDO'],
            ['codigo' => '240207', 'departamento' => 'AREQUIPA', 'provincia' => 'CAMANA', 'distrito' => 'PUNTA DE BOMBONES'],
            ['codigo' => '240208', 'departamento' => 'AREQUIPA', 'provincia' => 'CAMANA', 'distrito' => 'QUIÑONEZ'],
            ['codigo' => '240301', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'CHIVAY'],
            ['codigo' => '240302', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'ACARI'],
            ['codigo' => '240303', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'ANDUA'],
            ['codigo' => '240304', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'CAYLLOMA'],
            ['codigo' => '240305', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'COPA'],
            ['codigo' => '240306', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'HUASCO'],
            ['codigo' => '240307', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'ICHUPAMPA'],
            ['codigo' => '240308', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'LARI'],
            ['codigo' => '240309', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'LLUTA'],
            ['codigo' => '240310', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'MACA'],
            ['codigo' => '240311', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'MADRIGAL'],
            ['codigo' => '240312', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'SAN ANTONIO DE CHUCA'],
            ['codigo' => '240313', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'SIBAYO'],
            ['codigo' => '240314', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'TUTI'],
            ['codigo' => '240315', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'YANQUE'],
            ['codigo' => '240316', 'departamento' => 'AREQUIPA', 'provincia' => 'CAYLLOMA', 'distrito' => 'YOZA'],
            
            // Cusco
            ['codigo' => '250101', 'departamento' => 'CUSCO', 'provincia' => 'CUSCO', 'distrito' => 'CUSCO'],
            ['codigo' => '250102', 'departamento' => 'CUSCO', 'provincia' => 'CUSCO', 'distrito' => 'CCORCCA'],
            ['codigo' => '250103', 'departamento' => 'CUSCO', 'provincia' => 'CUSCO', 'distrito' => 'PORO'],
            ['codigo' => '250104', 'departamento' => 'CUSCO', 'provincia' => 'CUSCO', 'distrito' => 'SAN JERONIMO'],
            ['codigo' => '250105', 'departamento' => 'CUSCO', 'provincia' => 'CUSCO', 'distrito' => 'SAN SEBASTIAN'],
            ['codigo' => '250106', 'departamento' => 'CUSCO', 'provincia' => 'CUSCO', 'distrito' => 'SANTIAGO'],
            ['codigo' => '250107', 'departamento' => 'CUSCO', 'provincia' => 'CUSCO', 'distrito' => 'SAYLLA'],
            ['codigo' => '250108', 'departamento' => 'CUSCO', 'provincia' => 'CUSCO', 'distrito' => 'TOMEBAMBA'],
            ['codigo' => '250109', 'departamento' => 'CUSCO', 'provincia' => 'CUSCO', 'distrito' => 'WANCHAQ'],
            ['codigo' => '250201', 'departamento' => 'CUSCO', 'provincia' => 'ACOMAYO', 'distrito' => 'ACOMAYO'],
            ['codigo' => '250202', 'departamento' => 'CUSCO', 'provincia' => 'ACOMAYO', 'distrito' => 'CUSIPATA'],
            ['codigo' => '250203', 'departamento' => 'CUSCO', 'provincia' => 'ACOMAYO', 'distrito' => 'HUAROCHIRI'],
            ['codigo' => '250204', 'departamento' => 'CUSCO', 'provincia' => 'ACOMAYO', 'distrito' => 'LIMATAMBO'],
            ['codigo' => '250205', 'departamento' => 'CUSCO', 'provincia' => 'ACOMAYO', 'distrito' => 'MORROPE'],
            ['codigo' => '250206', 'departamento' => 'CUSCO', 'provincia' => 'ACOMAYO', 'distrito' => 'MUÑAPUCRO'],
            ['codigo' => '250207', 'departamento' => 'CUSCO', 'provincia' => 'ACOMAYO', 'distrito' => 'PISAC'],
            ['codigo' => '250208', 'departamento' => 'CUSCO', 'provincia' => 'ACOMAYO', 'distrito' => 'TARAY'],
            ['codigo' => '250209', 'departamento' => 'CUSCO', 'provincia' => 'ACOMAYO', 'distrito' => 'YUCay'],
            ['codigo' => '250301', 'departamento' => 'CUSCO', 'provincia' => 'QUILLLLACO', 'distrito' => 'ANTA'],
            ['codigo' => '250302', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'ANTAHUAMANCO'],
            ['codigo' => '250303', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'CACHIMAYO'],
            ['codigo' => '250304', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'CCEPITAPATA'],
            ['codigo' => '250305', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'CHECACUPE'],
            ['codigo' => '250306', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'CHEQUERE'],
            ['codigo' => '250307', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'CHINCHERO'],
            ['codigo' => '250308', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'COLLOTA'],
            ['codigo' => '250309', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'COSTAMIENTO'],
            ['codigo' => '250310', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'CUSCUDEN'],
            ['codigo' => '250311', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'HUAYLLABAMCO'],
            ['codigo' => '250312', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'LARAPA'],
            ['codigo' => '250313', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'LIMPE'],
            ['codigo' => '250314', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'MARAS'],
            ['codigo' => '250315', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'MORAS'],
            ['codigo' => '250316', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'PAMUCHA'],
            ['codigo' => '250317', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'QUILLLLACO'],
            ['codigo' => '250318', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'SAN SALVADOR'],
            ['codigo' => '250319', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'SANTA LUCIA'],
            ['codigo' => '250320', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'TINTAYA'],
            ['codigo' => '250321', 'departamento' => 'CUSCO', 'provincia' => 'QUILLABAMCO', 'distrito' => 'URCOS'],
            
            // Cajamarca
            ['codigo' => '260101', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'CAJAMARCA'],
            ['codigo' => '260102', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'ASUNCION'],
            ['codigo' => '260103', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'CHETILLA'],
            ['codigo' => '260104', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'COSPAN'],
            ['codigo' => '260105', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'ENCAÑADA'],
            ['codigo' => '260106', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'JESUS'],
            ['codigo' => '260107', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'LLacanora'],
            ['codigo' => '260108', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'LOS BAÑOS DEL INCA'],
            ['codigo' => '260109', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'MAGDALENA'],
            ['codigo' => '260110', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'MATARA'],
            ['codigo' => '260111', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'NAMORA'],
            ['codigo' => '260112', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJAMARCA', 'distrito' => 'SAN JUAN'],
            ['codigo' => '260201', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJATAMBO', 'distrito' => 'CAJATAMBO'],
            ['codigo' => '260202', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJATAMBO', 'distrito' => 'CAJABAMBA'],
            ['codigo' => '260203', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJATAMBO', 'distrito' => 'CALLEJON'],
            ['codigo' => '260204', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJATAMBO', 'distrito' => 'CHUGUR'],
            ['codigo' => '260205', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJATAMBO', 'distrito' => 'LA PARIANA'],
            ['codigo' => '260206', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJATAMBO', 'distrito' => 'LA TAPONA'],
            ['codigo' => '260207', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJATAMBO', 'distrito' => 'LOS OCHO PUERTOS'],
            ['codigo' => '260208', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJATAMBO', 'distrito' => 'PATOR'],
            ['codigo' => '260209', 'departamento' => 'CAJAMARCA', 'provincia' => 'CAJATAMBO', 'distrito' => 'SAN JUAN DE LA ESPERANZA'],
            ['codigo' => '260301', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'CELENDIN'],
            ['codigo' => '260302', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'CHANTA'],
            ['codigo' => '260303', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'CHICUOS'],
            ['codigo' => '260304', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'CORTEGANA'],
            ['codigo' => '260305', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'HUASMIN'],
            ['codigo' => '260306', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'JORGE CHAVEZ'],
            ['codigo' => '260307', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'MARIANO MELGAR'],
            ['codigo' => '260308', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'OXAMARCA'],
            ['codigo' => '260309', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'PICHANCHA'],
            ['codigo' => '260310', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'POLVORA'],
            ['codigo' => '260311', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'QUINUERA'],
            ['codigo' => '260312', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'SAN BERNARDO'],
            ['codigo' => '260313', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'SAN SILVESTRE'],
            ['codigo' => '260314', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'SANTA ROSA'],
            ['codigo' => '260315', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'SINA'],
            ['codigo' => '260316', 'departamento' => 'CAJAMARCA', 'provincia' => 'CELENDIN', 'distrito' => 'TOTORA'],
            
            // Ancash
            ['codigo' => '270101', 'departamento' => 'ANCASH', 'provincia' => 'HUARAZ', 'distrito' => 'HUARAZ'],
            ['codigo' => '270102', 'departamento' => 'ANCASH', 'provincia' => 'HUARAZ', 'distrito' => 'COJUP'],
            ['codigo' => '270103', 'departamento' => 'ANCASH', 'provincia' => 'HUARAZ', 'distrito' => 'HUANCHAY'],
            ['codigo' => '270104', 'departamento' => 'ANCASH', 'provincia' => 'HUARAZ', 'distrito' => 'INDEPENDENCIA'],
            ['codigo' => '270105', 'departamento' => 'ANCASH', 'provincia' => 'HUARAZ', 'distrito' => 'LAMAS'],
            ['codigo' => '270106', 'departamento' => 'ANCASH', 'provincia' => 'HUARAZ', 'distrito' => 'PAMPLONA'],
            ['codigo' => '270107', 'departamento' => 'ANCASH', 'provincia' => 'HUARAZ', 'distrito' => 'SANTA CRUZ'],
            ['codigo' => '270108', 'departamento' => 'ANCASH', 'provincia' => 'HUARAZ', 'distrito' => 'TINCO'],
            ['codigo' => '270109', 'departamento' => 'ANCASH', 'provincia' => 'HUARAZ', 'distrito' => 'YUNGAR'],
            ['codigo' => '270201', 'departamento' => 'ANCASH', 'provincia' => 'AIJA', 'distrito' => 'AIJA'],
            ['codigo' => '270202', 'departamento' => 'ANCASH', 'provincia' => 'AIJA', 'distrito' => 'AJJA'],
            ['codigo' => '270203', 'departamento' => 'ANCASH', 'provincia' => 'AIJA', 'distrito' => 'CORAC'],
            ['codigo' => '270204', 'departamento' => 'ANCASH', 'provincia' => 'AIJA', 'distrito' => 'HUACUY'],
            ['codigo' => '270205', 'departamento' => 'ANCASH', 'provincia' => 'AIJA', 'distrito' => 'HUILLCA'],
            ['codigo' => '270206', 'departamento' => 'ANCASH', 'provincia' => 'AIJA', 'distrito' => 'LLAMELLIN'],
            ['codigo' => '270207', 'departamento' => 'ANCASH', 'provincia' => 'AIJA', 'distrito' => 'PACHANGARA'],
            ['codigo' => '270301', 'departamento' => 'ANCASH', 'provincia' => 'BOLOGNESI', 'distrito' => 'CHIQUIAN'],
            ['codigo' => '270302', 'departamento' => 'ANCASH', 'provincia' => 'BOLOGNESI', 'distrito' => 'ABELARDO PARDO'],
            ['codigo' => '270303', 'departamento' => 'ANCASH', 'provincia' => 'BOLOGNESI', 'distrito' => 'CANIS'],
            ['codigo' => '270304', 'departamento' => 'ANCASH', 'provincia' => 'BOLOGNESI', 'distrito' => 'COLQUIOC'],
            ['codigo' => '270305', 'departamento' => 'ANCASH', 'provincia' => 'BOLOGNESI', 'distrito' => 'HUASTA'],
            ['codigo' => '270306', 'departamento' => 'ANCASH', 'provincia' => 'BOLOGNESI', 'distrito' => 'MAJES'],
            ['codigo' => '270307', 'departamento' => 'ANCASH', 'provincia' => 'BOLOGNESI', 'distrito' => 'QUIQUIJANA'],
            
            // Ica
            ['codigo' => '280101', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'ICA'],
            ['codigo' => '280102', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'LA TINGUIÑA'],
            ['codigo' => '280103', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'LOS AQUIJES'],
            ['codigo' => '280104', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'MAPASO'],
            ['codigo' => '280105', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'OCUCAJE'],
            ['codigo' => '280106', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'PACHACUTEC'],
            ['codigo' => '280107', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'PUEBLO NUEVO'],
            ['codigo' => '280108', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'SALAS'],
            ['codigo' => '280109', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'SAN JUAN DE CACIQUE'],
            ['codigo' => '280110', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'SANTA CRUZ'],
            ['codigo' => '280111', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'SANTIAGO'],
            ['codigo' => '280112', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'SUBTIA'],
            ['codigo' => '280113', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'TATE'],
            ['codigo' => '280114', 'departamento' => 'ICA', 'provincia' => 'ICA', 'distrito' => 'YAUCA DEL ROSARIO'],
            ['codigo' => '280201', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'CHINCHA ALTA'],
            ['codigo' => '280202', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'ALLAUCAS'],
            ['codigo' => '280203', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'CHAVIN'],
            ['codigo' => '280204', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'CHINCHA BAJA'],
            ['codigo' => '280205', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'EL INGENIO'],
            ['codigo' => '280206', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'MALA'],
            ['codigo' => '280207', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'PUEBLO NUEVO'],
            ['codigo' => '280208', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'SAN PEDRO DE HUACRACHANA'],
            ['codigo' => '280209', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'SANTA ROSA DE ACHUEL'],
            ['codigo' => '280210', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'TANTA'],
            ['codigo' => '280211', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'TOMEPAMAPA'],
            ['codigo' => '280212', 'departamento' => 'ICA', 'provincia' => 'CHINCHA', 'distrito' => 'YAUCA'],
            ['codigo' => '280301', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'NAZCA'],
            ['codigo' => '280302', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'CHANGUILLO'],
            ['codigo' => '280303', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'EL INGENIO'],
            ['codigo' => '280304', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'HUACACHINA'],
            ['codigo' => '280305', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'ILLAPO'],
            ['codigo' => '280306', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'MOSTAZA'],
            ['codigo' => '280307', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'PAMPA DE NAZCA'],
            ['codigo' => '280308', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'POROCHE'],
            ['codigo' => '280309', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'PUEBLO NUEVO'],
            ['codigo' => '280310', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'RIO GRANDE'],
            ['codigo' => '280311', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'SAN CESAR'],
            ['codigo' => '280312', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'SANTA FE'],
            ['codigo' => '280313', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'SANTIAGO'],
            ['codigo' => '280314', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'SOCABAYA'],
            ['codigo' => '280315', 'departamento' => 'ICA', 'provincia' => 'NAZCA', 'distrito' => 'TANGAY'],
            ['codigo' => '280401', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'PALPA'],
            ['codigo' => '280402', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'CAYETAME'],
            ['codigo' => '280403', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'CHANCA'],
            ['codigo' => '280404', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'LLANATA'],
            ['codigo' => '280405', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'LIPID'],
            ['codigo' => '280406', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'PALPA'],
            ['codigo' => '280407', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'PULIDO'],
            ['codigo' => '280408', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'QUILCA'],
            ['codigo' => '280409', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'RECTA'],
            ['codigo' => '280410', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'RIMAC'],
            ['codigo' => '280411', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'SAN JACINTO'],
            ['codigo' => '280412', 'departamento' => 'ICA', 'provincia' => 'PALPA', 'distrito' => 'SAN JUAN'],
            ['codigo' => '280501', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'PISCO'],
            ['codigo' => '280502', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'AMARA'],
            ['codigo' => '280503', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'ARCATA'],
            ['codigo' => '280504', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'AYAVI'],
            ['codigo' => '280505', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'BERNAL'],
            ['codigo' => '280506', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'BUENAVENTURA'],
            ['codigo' => '280507', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'CALLACAN'],
            ['codigo' => '280508', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'CAPILLAS'],
            ['codigo' => '280509', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'CASTILLO'],
            ['codigo' => '280510', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'CAWAYNE'],
            ['codigo' => '280511', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'CERRO AZUL'],
            ['codigo' => '280512', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'CHUNCHANGAL'],
            ['codigo' => '280513', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'CIENEGUILLA'],
            ['codigo' => '280514', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'COAYANTE'],
            ['codigo' => '280515', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'COLONIA'],
            ['codigo' => '280516', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'EL CATOLICO'],
            ['codigo' => '280517', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'EL CARMEN'],
            ['codigo' => '280518', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'HUANCANO'],
            ['codigo' => '280519', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'HUINIS'],
            ['codigo' => '280520', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'INDEPENDENCIA'],
            ['codigo' => '280521', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'JERES'],
            ['codigo' => '280522', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'LETRAY'],
            ['codigo' => '280523', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'LONGUIDA'],
            ['codigo' => '280524', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'MALLONES'],
            ['codigo' => '280525', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'MILAGRO'],
            ['codigo' => '280526', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'MONTE SERRA'],
            ['codigo' => '280527', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'ONTIVES'],
            ['codigo' => '280528', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'PACHACUTEC'],
            ['codigo' => '280529', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'PALACOS'],
            ['codigo' => '280530', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'PARACAS'],
            ['codigo' => '280531', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'PASIS'],
            ['codigo' => '280532', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'PICHICHA'],
            ['codigo' => '280533', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'PISCO'],
            ['codigo' => '280534', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'PRUNA'],
            ['codigo' => '280535', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'PUNTA PICHINCHA'],
            ['codigo' => '280536', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'QUILCA'],
            ['codigo' => '280537', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'RAMADILLA'],
            ['codigo' => '280538', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'RIO BLANCO'],
            ['codigo' => '280539', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'SALES'],
            ['codigo' => '280540', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'SAN ANDRÉS'],
            ['codigo' => '280541', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'SAN IGNACIO'],
            ['codigo' => '280542', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'SAN JUAN DE CASTILLA'],
            ['codigo' => '280543', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'SANTA CRUZ DE TUPAC AMARU'],
            ['codigo' => '280544', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'SANTA LUIA'],
            ['codigo' => '280545', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'SANTA ROSA DE PISCO'],
            ['codigo' => '280546', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'SAYAURE'],
            ['codigo' => '280547', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'TACAMA'],
            ['codigo' => '280548', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'TANQUES'],
            ['codigo' => '280549', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'TICACON'],
            ['codigo' => '280550', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'TIPAN'],
            ['codigo' => '280551', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'ULLU'],
            ['codigo' => '280552', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'UNIDAD'],
            ['codigo' => '280553', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'URBINAS'],
            ['codigo' => '280554', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'VILLA ARELLANO'],
            ['codigo' => '280555', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'VISTA ALEGRE'],
            ['codigo' => '280556', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'YABAD'],
            ['codigo' => '280557', 'departamento' => 'ICA', 'provincia' => 'PISCO', 'distrito' => 'YAUCA DEL CHILCA'],
            
            // Junin
            ['codigo' => '290101', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'HUANCAYO'],
            ['codigo' => '290102', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'CHICRAMA'],
            ['codigo' => '290103', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'CHILCA'],
            ['codigo' => '290104', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'EL TINGO'],
            ['codigo' => '290105', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'HUASICANCAN'],
            ['codigo' => '290106', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'INGENIO'],
            ['codigo' => '290107', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'MANZANAR'],
            ['codigo' => '290108', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'MARCO'],
            ['codigo' => '290109', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'MATSEL'],
            ['codigo' => '290110', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'NARANAN'],
            ['codigo' => '290111', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'POBLADO'],
            ['codigo' => '290112', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'QUILCAS'],
            ['codigo' => '290113', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'QUINCAN'],
            ['codigo' => '290114', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'SAN AGUSTIN'],
            ['codigo' => '290115', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'SAN CARLOS'],
            ['codigo' => '290116', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'SANTO DOMINGO DE ACOBAMBA'],
            ['codigo' => '290117', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'SAÑO'],
            ['codigo' => '290118', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'SIBAMBO'],
            ['codigo' => '290119', 'departamento' => 'JUNIN', 'provincia' => 'HUANCAYO', 'distrito' => 'TICAPAMPO'],
            
            // Amazonas
            ['codigo' => '300101', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'CHACHAPOYAS'],
            ['codigo' => '300102', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'ASUNCIÓN'],
            ['codigo' => '300103', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'BALSAS'],
            ['codigo' => '300104', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'CHETO'],
            ['codigo' => '300105', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'CHICHA'],
            ['codigo' => '300106', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'CHUQUIBAMBA'],
            ['codigo' => '300107', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'COROSHA'],
            ['codigo' => '300108', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'CUBIEB'],
            ['codigo' => '300109', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'GÓMEZ'],
            ['codigo' => '300110', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'GRUA'],
            ['codigo' => '300111', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'HUANCAS'],
            ['codigo' => '300112', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'LAJATA'],
            ['codigo' => '300113', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'LEVASO'],
            ['codigo' => '300114', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'LINERA'],
            ['codigo' => '300115', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'LLAMA'],
            ['codigo' => '300116', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'MARISCOS'],
            ['codigo' => '300117', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'MOLVINA'],
            ['codigo' => '300118', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'QUIGLIC'],
            ['codigo' => '300119', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'SAN CARLOS DE VALLETO'],
            ['codigo' => '300120', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'SAN COCHIM'],
            ['codigo' => '300121', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'SONDOR'],
            ['codigo' => '300122', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'SOTO'],
            ['codigo' => '300123', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'TISHBIO'],
            ['codigo' => '300124', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'UTCO'],
            ['codigo' => '300125', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'VALERA'],
            ['codigo' => '300126', 'departamento' => 'AMAZONAS', 'provincia' => 'CHACHAPOYAS', 'distrito' => 'VIGUD'],
            
            // San Martin
            ['codigo' => '310101', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'TARAPOTO'],
            ['codigo' => '310102', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'ALBERTO LEVEAU'],
            ['codigo' => '310103', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'CABALLOCANCHA'],
            ['codigo' => '310104', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'CHAZUTA'],
            ['codigo' => '310105', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'CHIPURANA'],
            ['codigo' => '310106', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'EL PORVENIR'],
            ['codigo' => '310107', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'HUIMBAYOC'],
            ['codigo' => '310108', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'JUAN GUERRA'],
            ['codigo' => '310109', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'LA BANDA DE Shilcayo'],
            ['codigo' => '310110', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'PAPAPLAYA'],
            ['codigo' => '310111', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'PUNTUNATA'],
            ['codigo' => '310112', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'SANTA CRUZ'],
            ['codigo' => '310113', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'SANTA ELENA'],
            ['codigo' => '310114', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'SAN AGUSTIN'],
            ['codigo' => '310115', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'BELLA VISTA'],
            ['codigo' => '310116', 'departamento' => 'SAN MARTIN', 'provincia' => 'TARAPOTO', 'distrito' => 'TINGO NEGRO'],
            ['codigo' => '310201', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'MOYOBAMBO'],
            ['codigo' => '310202', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'CALZADA'],
            ['codigo' => '310203', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'HIGOS'],
            ['codigo' => '310204', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'HUAYUNGA'],
            ['codigo' => '310205', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'JEPELACIO'],
            ['codigo' => '310206', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'MOYOBAMBO'],
            ['codigo' => '310207', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'PACAYZAPA'],
            ['codigo' => '310208', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'SAN FERNANDO'],
            ['codigo' => '310209', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'SAN MATEO'],
            ['codigo' => '310210', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'SAYTA'],
            ['codigo' => '310211', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'SISA'],
            ['codigo' => '310212', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'TABALOSOS'],
            ['codigo' => '310213', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'TAMBOLGA'],
            ['codigo' => '310214', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'TINGO'],
            ['codigo' => '310215', 'departamento' => 'SAN MARTIN', 'provincia' => 'MOYOBAMBO', 'distrito' => 'TOCACHE'],
            
            // Loreto
            ['codigo' => '320101', 'departamento' => 'LORETO', 'provincia' => 'MAYNAS', 'distrito' => 'IQUITOS'],
            ['codigo' => '320102', 'departamento' => 'LORETO', 'provincia' => 'MAYNAS', 'distrito' => 'INDIANA'],
            ['codigo' => '320103', 'departamento' => 'LORETO', 'provincia' => 'MAYNAS', 'distrito' => 'PUNCHANA'],
            ['codigo' => '320104', 'departamento' => 'LORETO', 'provincia' => 'MAYNAS', 'distrito' => 'BELEN'],
            ['codigo' => '320105', 'departamento' => 'LORETO', 'provincia' => 'MAYNAS', 'distrito' => 'SAN JUAN BAUTISTA'],
            ['codigo' => '320106', 'departamento' => 'LORETO', 'provincia' => 'MAYNAS', 'distrito' => 'TABLITOS'],
            ['codigo' => '320107', 'departamento' => 'LORETO', 'provincia' => 'MAYNAS', 'distrito' => 'TORRES CAUSA'],
            ['codigo' => '320108', 'departamento' => 'LORETO', 'provincia' => 'MAYNAS', 'distrito' => 'CALLERIA'],
            ['codigo' => '320109', 'departamento' => 'LORETO', 'provincia' => 'MAYNAS', 'distrito' => 'CARHOUT'],
            ['codigo' => '320201', 'departamento' => 'LORETO', 'provincia' => 'ALTO AMAZONAS', 'distrito' => 'YURUA'],
            ['codigo' => '320202', 'departamento' => 'LORETO', 'provincia' => 'ALTO AMAZONAS', 'distrito' => 'NAUTA'],
            ['codigo' => '320203', 'departamento' => 'LORETO', 'provincia' => 'ALTO AMAZONAS', 'distrito' => 'PARINARI'],
            ['codigo' => '320204', 'departamento' => 'LORETO', 'provincia' => 'ALTO AMAZONAS', 'distrito' => 'JENARO HERRERA'],
            ['codigo' => '320205', 'departamento' => 'LORETO', 'provincia' => 'ALTO AMAZONAS', 'distrito' => 'YAQUERENA'],
            ['codigo' => '320206', 'departamento' => 'LORETO', 'provincia' => 'ALTO AMAZONAS', 'distrito' => 'SARHUE'],
            ['codigo' => '320207', 'departamento' => 'LORETO', 'provincia' => 'LORETO', 'distrito' => 'CONTAMANA'],
            ['codigo' => '320208', 'departamento' => 'LORETO', 'provincia' => 'LORETO', 'distrito' => 'INIA'],
            ['codigo' => '320209', 'departamento' => 'LORETO', 'provincia' => 'LORETO', 'distrito' => 'PADRE MARQUEZ'],
            ['codigo' => '320210', 'departamento' => 'LORETO', 'provincia' => 'LORETO', 'distrito' => 'PASTAZA'],
            ['codigo' => '320211', 'departamento' => 'LORETO', 'provincia' => 'LORETO', 'distrito' => 'PUTUMAYO'],
            ['codigo' => '320212', 'departamento' => 'LORETO', 'provincia' => 'LORETO', 'distrito' => 'RIO TIGRILLO'],
            ['codigo' => '320213', 'departamento' => 'LORETO', 'provincia' => 'DATEM DEL MARAÑON', 'distrito' => 'BAGAZAN'],
            
            // Puno
            ['codigo' => '330101', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'PUNO'],
            ['codigo' => '330102', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'ACORA'],
            ['codigo' => '330103', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'ASILLO'],
            ['codigo' => '330104', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'ATUNCOLLA'],
            ['codigo' => '330105', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'CAPACHICA'],
            ['codigo' => '330106', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'CHUIPE'],
            ['codigo' => '330107', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'COATA'],
            ['codigo' => '330108', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'COMANA'],
            ['codigo' => '330109', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'CONIMA'],
            ['codigo' => '330110', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'HUATA'],
            ['codigo' => '330111', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'HUACAYO'],
            ['codigo' => '330112', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'ICHU'],
            ['codigo' => '330113', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'ILAVE'],
            ['codigo' => '330114', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'JULI'],
            ['codigo' => '330115', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'KELLUYO'],
            ['codigo' => '330116', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'KHAPILLA'],
            ['codigo' => '330117', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'MAÑAZO'],
            ['codigo' => '330118', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'PAUCARCOLLA'],
            ['codigo' => '330119', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'PICHACANI'],
            ['codigo' => '330120', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'PILCUYO'],
            ['codigo' => '330121', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'POMO'],
            ['codigo' => '330122', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'PRAZA'],
            ['codigo' => '330123', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'PUCARA'],
            ['codigo' => '330124', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'QUITEATA'],
            ['codigo' => '330125', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'RINRICA'],
            ['codigo' => '330126', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'SINA'],
            ['codigo' => '330127', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'SAN ANTONIO'],
            ['codigo' => '330128', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'SANTA LUCIA'],
            ['codigo' => '330129', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'TAPAQUILLO'],
            ['codigo' => '330130', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'TARACO'],
            ['codigo' => '330131', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'TICLACOYAN'],
            ['codigo' => '330132', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'TINAQUERA'],
            ['codigo' => '330133', 'departamento' => 'PUNO', 'provincia' => 'PUNO', 'distrito' => 'YACANGO'],
        ];

        foreach ($ubigeos as $ubigeo) {
            Ubigeo::updateOrCreate(
                ['codigo' => $ubigeo['codigo']],
                $ubigeo
            );
        }
    }
}